ROOT_DIRECTORY_NAME = "_fcm"
DATABASE_NAME = "test.sqlite"

ARTIFACT_CATEGORIES = [
    (1, "APPLICATION_EXECUTION"),
    (2, "FILE_FOLDER_OPENING"),
    (3, "DELETED_ITEMS_FILE_EXISTENCE"),
    (4, "BROWSER_ACTIVITY"),
    (5, "CLOUD_STORAGE"),
    (6, "ACCOUNT_USAGE"),
    (7, "NETWORK_ACTIVITY_PHYSICAL_LOCATION"),
    (8, "SYSTEM_INFORMATION"),
    (9, "EXTERNAL_DEVICE_USB_USAGE"),
]
