from pathlib import Path

current_directory = Path(__file__).parent.absolute()


# Root Directory Name
ROOT_DIRECTORY_NAME = "_fcm"

# Database Name
DATABASE_NAME = "forensic_data.sqlite"

# Artifact Schema
ARTIFACT_SCHEMA_FILESYSTEM = current_directory / "schema" / "filesystem"
ARTIFACT_SCHEMA_WINDOWS = current_directory / "schema" / "windows"
ARTIFACT_SCHEMA_REGISTRY = current_directory / "schema" / "windows" / "registry"
ARTIFACT_SCHEMA_BROWSER = current_directory / "schema" / "application" / "browsers"

# Categories
CAT_APPLICATION_EXECUTION = "APPLICATION_EXECUTION"
CAT_FILE_FOLDER_OPENING = "FILE_FOLDER_OPENING"
CAT_DELETED_ITEMS_FILE_EXISTENCE = "DELETED_ITEMS_FILE_EXISTENCE"
CAT_BROWSER_ACTIVITY = "BROWSER_ACTIVITY"
CAT_CLOUD_STORAGE = "CLOUD_STORAGE"
CAT_ACCOUNT_USAGE = "ACCOUNT_USAGE"
CAT_NETWORK_ACTIVITY_PHYSICAL_LOCATION = "NETWORK_ACTIVITY_PHYSICAL_LOCATION"
CAT_SYSTEM_INFORMATION = "SYSTEM_INFORMATION"
CAT_EXTERNAL_DEVICE_USB_USAGE = "EXTERNAL_DEVICE_USB_USAGE"

# ! Artifacts: program input(artifact) must be same as these artifact name
ART_CHROME = "chrome"
ART_EDGE = "edge"
ART_IEXPLORER = "iexplorer"
ART_MFT = "mft"
ART_USNJRNL = "usnjrnl"
ART_RECYCLEBIN = "recyclebin"
ART_PREFETCH = "prefetch"
ART_SRU_NETWORK = "sru_network"
ART_SRU_APPLICATION = "sru_application"
ART_FILE_HISTORY = "file_history"
ART_THUMBCACHE = "thumbcache"
ART_JUMPLIST = "jumplist"
ART_WINDOWS_TIMELINE = "windows_timeline"
ART_EVENT_LOGON = "event_logon"
ART_EVENT_USB = "event_usb"
ART_EVENT_WLAN = "event_wlan"
ART_AMCACHE = "amcache"
ART_REGISTRY_USER_ACCOUNT = "reg_user_account"
ART_REGISTRY_USERASSIST = "reg_userassist"
ART_REGISTRY_SHIMCACHE = "reg_shimcache"
ART_REGISTRY_BAM = "reg_bam"
ART_NETWORK_INFO = "network_info"
ART_SHELLBAGS = "shellbags"
ART_REGISTRY_USB = "reg_usb"
ART_REGISTRY_AUTORUN = "reg_autorun"
ART_SYSTEM_INFO = "system_info"
ART_MRU = "mru"

# ! Parsed Artifact Result Name: the name for "result" from 'parse()' method (ForensicArtifact)
RSLT_CHROME_HISTORY = "chrome_history"
RSLT_CHROME_DOWNLOADS = "chrome_downloads"
RSLT_CHROME_KEYWORD_SEARCH_TERMS = "chrome_keyword_search_terms"
RSLT_CHROME_AUTOFILL = "chrome_autofill"
RSLT_CHROME_LOGIN_DATA = "chrome_login_data"
RSLT_CHROME_BOOKMARKS = "chrome_bookmarks"
RSLT_EDGE_HISTORY = "edge_history"
RSLT_EDGE_DOWNLOADS = "edge_downloads"
RSLT_EDGE_KEYWORD_SEARCH_TERMS = "edge_keyword_search_terms"
RSLT_EDGE_AUTOFILL = "edge_autofill"
RSLT_EDGE_LOGIN_DATA = "edge_login_data"
RSLT_EDGE_BOOKMARKS = "edge_bookmarks"
RSLT_IEXPLORER_HISTORY = "iexplorer_history"
RSLT_IEXPLORER_DOWNLOADS = "iexplorer_downloads"
RSLT_MFT = "mft"
RSLT_USNJRNL = "usnjrnl"
RSLT_RECYCLEBIN = "recyclebin"
RSLT_PREFETCH = "prefetch"
RSLT_SRU_NETWORK_CONNECTIVITY = "sru_network_connectivity"
RSLT_SRU_NETWORK_DATA = "sru_network_data"
RSLT_SRU_APPLICATION = "sru_application"
RSLT_SRU_APPLICATION_TIMELINE = "sru_application_timeline"
RSLT_FILE_HISTORY = "file_history"
RSLT_THUMBCACHE = "thumbcache"
RSLT_ICONCACHE = "iconcache"
RSLT_JUMPLIST = "jumplist"
RSLT_WINDOWS_TIMELINE = "windows_timeline"
RSLT_EVENT_LOGON = "event_logon"
RSLT_EVENT_USB = "event_usb"
RSLT_EVENT_WLAN = "event_wlan"
RSLT_AMCACHE = "amcache"
RSLT_REGISTRY_USER_ACCOUNT_SAM = "reg_user_account_sam"
RSLT_REGISTRY_USER_ACCOUNT_PROFILELIST = "reg_user_account_profilelist"
RSLT_REGISTRY_USERASSIST = "reg_userassist"
RSLT_REGISTRY_USB = "reg_usb"
RSLT_REGISTRY_BAM = "reg_bam"
RSLT_REGISTRY_SHIMCACHE = "reg_shimcache"
RSLT_REGISTRY_AUTORUN = "reg_autorun"
