Name: Amcache Registry
Desc: Amcache application files data from the Windows Registry
Table:
  TableName: reg_amcache_application_files
  Columns:
    - id: "INTEGER PRIMARY KEY AUTOINCREMENT"
    - link_date: "TEXT"
    - name: "TEXT"
    - size: "INTEGER"
    - publisher: "TEXT"
    - product_name: "TEXT"
    - bin_file_version: "TEXT"
    - product_version: "TEXT"
    - bin_product_version: "TEXT"
    - version: "TEXT"
    - program_id: "TEXT"
    - path: "TEXT"
    - mtime_regf: "TEXT"
    - hash_path: "TEXT"
    - digests: "TEXT"
    - language: "TEXT"
    - is_pefile: "INTEGER"
    - is_oscomponent: "INTEGER"
    - evidence_id: "TEXT"