Name: Amcache Registry
Desc: Amcache application data from the Windows Registry
Table:
  - TableName: reg_amcache_applications
    Columns:
      - id: [INTEGER PRIMARY KEY AUTOINCREMENT]
      - install_date: [TEXT]
      - name: [TEXT]
      - type: [TEXT]
      - publisher: [TEXT]
      - uninstall_string: [TEXT]
      - root_dir_path: [TEXT]
      - program_id: [TEXT]
      - program_instance_id: [TEXT]
      - msi_package_code: [TEXT]
      - msi_product_code: [TEXT]
      - mtime_regf: [TEXT]
      - install_date_arp_last_modified: [TEXT]
      - install_date_from_link_file: [TEXT]
      - os_version_at_install_time: [TEXT]
      - language_code: [TEXT]
      - package_full_name: [TEXT]
      - manifest_path: [TEXT]
      - registry_key_path: [TEXT]
      - source: [TEXT]
      - evidence_id: [TEXT]
