from enum import Enum


class Artifact(Enum):
    APP_CHROME = "app_chrome"
    APP_EDGE = "app_edge"
    APP_IEXPLORER = "app_iexplorer"
    FS_MFT = "fs_mft"
    FS_USNJRNL = "fs_usnjrnl"
    WIN_RECYCLEBIN = "win_recyclebin"
    WIN_PREFETCH = "win_prefetch"
    WIN_SRU_NETWORK = "win_sru_network"
    WIN_SRU_APPLICATION = "win_sru_application"
    WIN_FILE_HISTORY = "win_file_history"
    WIN_THUMBCACHE = "win_thumbcache"
    WIN_JUMPLIST = "win_jumplist"
    WIN_WINDOWSTIMELINE = "win_windowstimeline"
    WIN_EVENT_LOGON = "win_event_logon"
    WIN_EVENT_USB = "win_event_usb"
    WIN_EVENT_WLAN = "win_event_wlan"
    REG_AMCACHE = "reg_amcache"
    REG_USERACCOUNT = "reg_useraccount"
    REG_USERASSIST = "reg_userassist"
    REG_SHIMCACHE = "reg_shimcache"
    REG_BAM = "reg_bam"
    REG_NETWORKINFO = "reg_networkinfo"
    REG_SHELLBAGS = "reg_shellbags"
    REG_USB = "reg_usb"
    REG_AUTORUN = "reg_autorun"
    REG_SYSTEMINFO = "reg_systeminfo"
    REG_MRU = "reg_mru"


class Tables(Enum):
    REG_AMCACHE_APPLICATION = "reg_amcache_application"
    REG_AMCACHE_APPLICATION_FILE = "reg_amcache_application_file"
    REG_AMCACHE_FILE = "reg_amcache_file"
    REG_AMCACHE_PROGRAMS = "reg_amcache_programs"
    REG_AMCACHE_BINARY = "reg_amcache_binary"
    REG_AMCACHE_CONTAINER = "reg_amcache_container"
    REG_AMCACHE_SHORTCUT = "reg_amcache_shortcut"
    REG_AUTORUN = "reg_autorun"
    REG_BAM = "reg_bam"
    REG_NETWORKINFO = "reg_networkinfo"
    REG_SHELLBAGS = "reg_shellbags"
    REG_SHIMCACHE = "reg_shimcache"
    REG_SYSTEMINFO = "reg_systeminfo"
    REG_USB = "reg_usb"
    REG_USERACCOUNT = "reg_useraccount"
    REG_USERASSIST = "reg_userassist"
