from enum import Enum

# Database Name
DATABASE_NAME = "case.db"
LOGFILE_NAME = "test.log"

# Database Table Name
TABLE_NAME_FORENSIC_CASE = "forensic_case"
TABLE_NAME_EVIDENCES = "evidences"
TABLE_NAME_ARTIFACT_CATEGORY = "artifact_category"

# Artifact Path Owner
ARTIFACT_OWNER_SYSTEM = "SYSTEM"
ARTIFACT_OWNER_USER = "USER"

# Categories
CAT_APPLICATION_EXECUTION = "APPLICATION_EXECUTION"
CAT_FILE_FOLDER_OPENING = "FILE_FOLDER_OPENING"
CAT_DELETED_ITEMS_FILE_EXISTENCE = "DELETED_ITEMS_FILE_EXISTENCE"
CAT_BROWSER_ACTIVITY = "BROWSER_ACTIVITY"
CAT_CLOUD_STORAGE = "CLOUD_STORAGE"
CAT_ACCOUNT_USAGE = "ACCOUNT_USAGE"
CAT_NETWORK_ACTIVITY_PHYSICAL_LOCATION = "NETWORK_ACTIVITY_PHYSICAL_LOCATION"
CAT_SYSTEM_INFORMATION = "SYSTEM_INFORMATION"
CAT_EXTERNAL_DEVICE_USB_USAGE = "EXTERNAL_DEVICE_USB_USAGE"


# ! Artifacts: program input(artifact) must be same as these artifact name
class Artifact(Enum):
    APP_CHROME = "app_chrome"
    APP_EDGE = "app_edge"
    APP_IEXPLORER = "app_iexplorer"
    FS_MFT = "fs_mft"
    FS_USNJRNL = "fs_usnjrnl"
    WIN_RECYCLEBIN = "win_recyclebin"
    WIN_PREFETCH = "win_prefetch"
    WIN_SRU_NETWORK = "win_sru_network"
    WIN_SRU_APPLICATION = "win_sru_application"
    WIN_FILE_HISTORY = "win_file_history"
    WIN_THUMBCACHE = "win_thumbcache"
    WIN_JUMPLIST = "win_jumplist"
    WIN_WINDOWSTIMELINE = "win_windowstimeline"
    EVT_LOGON = "evt_logon"
    EVT_USB = "evt_usb"
    EVT_WLAN = "evt_wlan"
    REG_AMCACHE = "reg_amcache"
    REG_USERACCOUNT = "reg_useraccount"
    REG_USERASSIST = "reg_userassist"
    REG_SHIMCACHE = "reg_shimcache"
    REG_BAM = "reg_bam"
    REG_NETWORKINFO = "reg_networkinfo"
    REG_SHELLBAGS = "reg_shellbags"
    REG_USB = "reg_usb"
    REG_AUTORUN = "reg_autorun"
    REG_SYSTEMINFO = "reg_systeminfo"
    REG_MRU = "reg_mru"


ART_CHROME = "chrome"
ART_EDGE = "edge"
ART_IEXPLORER = "iexplorer"
ART_MFT = "mft"
ART_USNJRNL = "usnjrnl"
ART_RECYCLEBIN = "recyclebin"
ART_PREFETCH = "prefetch"
ART_SRU_NETWORK = "sru_network"
ART_SRU_APPLICATION = "sru_application"
ART_FILE_HISTORY = "file_history"
ART_THUMBCACHE = "thumbcache"
ART_JUMPLIST = "jumplist"
ART_WINDOWS_TIMELINE = "windows_timeline"
ART_EVENT_LOGON = "event_logon"
ART_EVENT_USB = "event_usb"
ART_EVENT_WLAN = "event_wlan"
ART_REGISTRY_AMCACHE = "reg_amcache"
ART_REGISTRY_USERACCOUNT = "reg_useraccount"
ART_REGISTRY_USERASSIST = "reg_userassist"
ART_REGISTRY_SHIMCACHE = "reg_shimcache"
ART_REGISTRY_BAM = "reg_bam"
ART_REGISTRY_NETWORKINFO = "reg_networkinfo"
ART_REGISTRY_SHELLBAGS = "reg_shellbags"
ART_REGISTRY_USB = "reg_usb"
ART_REGISTRY_AUTORUN = "reg_autorun"
ART_REGISTRY_SYSTEMINFO = "reg_systeminfo"
ART_MRU = "mru"
