# Database Name
DATABASE_NAME = "case.db"
LOGFILE_NAME = "test.log"

# Database Table Name
TABLE_NAME_FORENSIC_CASE = "forensic_case"
TABLE_NAME_EVIDENCES = "evidences"
TABLE_NAME_ARTIFACT_CATEGORY = "artifact_category"

# Artifact Path Owner
ARTIFACT_OWNER_SYSTEM = "SYSTEM"
ARTIFACT_OWNER_USER = "USER"

# Categories
CAT_APPLICATION_EXECUTION = "APPLICATION_EXECUTION"
CAT_FILE_FOLDER_OPENING = "FILE_FOLDER_OPENING"
CAT_DELETED_ITEMS_FILE_EXISTENCE = "DELETED_ITEMS_FILE_EXISTENCE"
CAT_BROWSER_ACTIVITY = "BROWSER_ACTIVITY"
CAT_CLOUD_STORAGE = "CLOUD_STORAGE"
CAT_ACCOUNT_USAGE = "ACCOUNT_USAGE"
CAT_NETWORK_ACTIVITY_PHYSICAL_LOCATION = "NETWORK_ACTIVITY_PHYSICAL_LOCATION"
CAT_SYSTEM_INFORMATION = "SYSTEM_INFORMATION"
CAT_EXTERNAL_DEVICE_USB_USAGE = "EXTERNAL_DEVICE_USB_USAGE"
