# Database Name
DATABASE_NAME = "case.db"
LOGFILE_NAME = "test.log"

# Database Table Name
TABLE_NAME_FORENSIC_CASE = "forensic_case"
TABLE_NAME_EVIDENCES = "evidences"
TABLE_NAME_ARTIFACT_CATEGORY = "artifact_category"

# Artifact Path Owner
ARTIFACT_OWNER_SYSTEM = "SYSTEM"
ARTIFACT_OWNER_USER = "USER"

# Categories
CAT_APPLICATION_EXECUTION = "APPLICATION_EXECUTION"
CAT_FILE_FOLDER_OPENING = "FILE_FOLDER_OPENING"
CAT_DELETED_ITEMS_FILE_EXISTENCE = "DELETED_ITEMS_FILE_EXISTENCE"
CAT_BROWSER_ACTIVITY = "BROWSER_ACTIVITY"
CAT_CLOUD_STORAGE = "CLOUD_STORAGE"
CAT_ACCOUNT_USAGE = "ACCOUNT_USAGE"
CAT_NETWORK_ACTIVITY_PHYSICAL_LOCATION = "NETWORK_ACTIVITY_PHYSICAL_LOCATION"
CAT_SYSTEM_INFORMATION = "SYSTEM_INFORMATION"
CAT_EXTERNAL_DEVICE_USB_USAGE = "EXTERNAL_DEVICE_USB_USAGE"


# ! Artifacts: program input(artifact) must be same as these artifact name

ART_CHROME = "chrome"
ART_EDGE = "edge"
ART_IEXPLORER = "iexplorer"
ART_MFT = "mft"
ART_USNJRNL = "usnjrnl"
ART_RECYCLEBIN = "recyclebin"
ART_PREFETCH = "prefetch"
ART_SRU_NETWORK = "sru_network"
ART_SRU_APPLICATION = "sru_application"
ART_FILE_HISTORY = "file_history"
ART_THUMBCACHE = "thumbcache"
ART_JUMPLIST = "jumplist"
ART_WINDOWS_TIMELINE = "windows_timeline"
ART_EVENT_LOGON = "event_logon"
ART_EVENT_USB = "event_usb"
ART_EVENT_WLAN = "event_wlan"
ART_REGISTRY_AMCACHE = "reg_amcache"
ART_REGISTRY_USERACCOUNT = "reg_useraccount"
ART_REGISTRY_USERASSIST = "reg_userassist"
ART_REGISTRY_SHIMCACHE = "reg_shimcache"
ART_REGISTRY_BAM = "reg_bam"
ART_REGISTRY_NETWORKINFO = "reg_networkinfo"
ART_REGISTRY_SHELLBAGS = "reg_shellbags"
ART_REGISTRY_USB = "reg_usb"
ART_REGISTRY_AUTORUN = "reg_autorun"
ART_REGISTRY_SYSTEMINFO = "reg_systeminfo"
ART_MRU = "mru"
