Name: SRU Application
Desc: Application Data extracted from the SRU Database
Table:
  - TableName: sru_application
    Columns:
      - id: [INTEGER PRIMARY KEY AUTOINCREMENT]
      - ts: [TEXT]
      - app: [TEXT]
      - user: [TEXT]
      - foreground_cycle_time: [INTEGER]
      - background_cycle_time: [INTEGER]
      - face_time: [INTEGER]
      - foreground_context_switches: [INTEGER]
      - background_context_switches: [INTEGER]
      - foreground_bytes_read: [INTEGER]
      - foreground_bytes_written: [INTEGER]
      - foreground_num_read_operations: [INTEGER]
      - foreground_num_write_operations: [INTEGER]
      - foreground_number_of_flushes: [INTEGER]
      - background_bytes_read: [INTEGER]
      - background_bytes_written: [INTEGER]
      - background_num_read_operations: [INTEGER]
      - background_num_write_operations: [INTEGER]
      - background_number_of_flushes: [INTEGER]
      - evidence_id: [TEXT]